const express = require('express');
const cors = require('cors');
require('dotenv').config();
const connectDB = require('./config/db');
const app = express();
connectDB();
app.use(cors());
app.use(express.json());
app.get('/', (req, res) => res.send('api working'));
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log(`server on port ${PORT}`));