const express = require('express');
const cors = require('cors');
require('dotenv').config();
const connectDB = require('./config/db');
const app = express();
connectDB();
const eventRoutes = require('./routes/eventRoutes');
app.use(cors());
app.use(express.json());
app.use('/api/events', eventRoutes);
app.get('/', (req, res) => res.send('api working'));
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log(`server on port ${PORT}`));
const authRoutes = require('./routes/authRoutes');
app.use('/api/auth', authRoutes);